// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InterestUIClient is the client API for InterestUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterestUIClient interface {
	// ListEngineSpecs returns a list of Interest Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (InterestUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type interestUIClient struct {
	cc grpc.ClientConnInterface
}

func NewInterestUIClient(cc grpc.ClientConnInterface) InterestUIClient {
	return &interestUIClient{cc}
}

func (c *interestUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (InterestUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &InterestUI_ServiceDesc.Streams[0], "/v1.InterestUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &interestUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InterestUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type interestUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *interestUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *interestUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.InterestUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterestUIServer is the server API for InterestUI service.
// All implementations must embed UnimplementedInterestUIServer
// for forward compatibility
type InterestUIServer interface {
	// ListEngineSpecs returns a list of Interest Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, InterestUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedInterestUIServer()
}

// UnimplementedInterestUIServer must be embedded to have forward compatible implementations.
type UnimplementedInterestUIServer struct {
}

func (UnimplementedInterestUIServer) ListEngineSpecs(*ListEngineSpecsRequest, InterestUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedInterestUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedInterestUIServer) mustEmbedUnimplementedInterestUIServer() {}

// UnsafeInterestUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterestUIServer will
// result in compilation errors.
type UnsafeInterestUIServer interface {
	mustEmbedUnimplementedInterestUIServer()
}

func RegisterInterestUIServer(s grpc.ServiceRegistrar, srv InterestUIServer) {
	s.RegisterService(&InterestUI_ServiceDesc, srv)
}

func _InterestUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InterestUIServer).ListEngineSpecs(m, &interestUIListEngineSpecsServer{stream})
}

type InterestUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type interestUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *interestUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InterestUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterestUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.InterestUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterestUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterestUI_ServiceDesc is the grpc.ServiceDesc for InterestUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterestUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.InterestUI",
	HandlerType: (*InterestUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _InterestUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _InterestUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "interest-ui.proto",
}
